eastgenomics/eggd_dias_batch

batch.py
script.py

Could be made more user friendly, but works. dx cd into the fastq dir and run batch.py to run all samples with fastqs in the directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/1)

Batch submission for Dias workflow

---

batch.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/2)

Fixed formatting error. Made batch run without confirmation

---

dias.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/6)

Added shebang. Required to lmod module to function

---

dias.py

Updated references to dynamic files to use latest approved files (all have been CAPAd).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/7)

Update file references

---

dias.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/8)

Updated vcf2xls app to v1.1.1

---

dias.py

Branched from v1.2.1 commit due to issues with missing sub-job output in v1.2.2. Will restore sub-jobs in future update once issue is resolved.
v1.2.3 will include udpated MultiQC app/config and updated vcf2xls app.
Updated references to these apps/files to use latest releases in 001.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/13)

Updated MultiQC app, MultiQC config, and vcf2xls app

---

dias.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/16)

Updated genes2transcripts file id to use updated g2t file

---

dias.py

Last commit contained id for compressed version of file (since upload agent automatically compresses files)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/17)

Update g2t file-id to use non-compressed file

---

dias.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/18)

Reanalysis

---

dias.py

Sentieon fastq input arrays need to be sorted such that the nth fq in the R1 array is paired with the nth fq in the R2 array. This PR sorts the arrays to ensure that this is the case.
i.e.
correct
R1 = [s1_R1_**L001**.fastq.gz, s1_R1_**L002**.fastq.gz]
R2 = [s1_R2_**L001**.fastq.gz, s1_R2_**L002**.fastq.gz]
incorrect
R1 = [s1_R1_**L001**.fastq.gz, s1_R1_**L002**.fastq.gz]
R2 = [s1_R2_**L002**.fastq.gz, s1_R2_**L001**.fastq.gz]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/20)

Fixed fq array sorting

---

dias.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/21)

Updated mqc config file reference to 1.0.4

---

dias.py

Now uses vcf2xls 1.2.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/22)

Updated vcf2xls applet reference

---

dias.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/23)

Updated multiQC applet reference

---

dias.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/24)

Made fq dict generation function search only within specified dir, rather than the entire project

---

config.py

I have broken the previous multi workflow so we had to recreate a new one.
I seek absolution for my sin, plz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/33)

use now fixed multi workflow id

---

dias.py

- Dry running
- Sample sheet necessary for running reports
- Check if all reports have been created
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/34)

v1.5.0 dias.py

---

multiqc.py

- dry running
- ignore reuse
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/38)

v1.5.0 multiqc

---

dias.py

- remove sample sheet for reports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/44)

v1.5.0 - dias.py - fix

---

config.py

- new workflow ids and stage ids for multi and reports
- staging dict for reports
- dynamic file dict for reports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/36)

v1.5.0 config

---

general_functions.py

- redundant functions made useful for multi and reports:
- make_workflow_out_dir
- get_stage_inputs
- prepare_batch_writing
- create_batch_file
- get index for athena reports:
- find_previous_coverage_reports
- get_next_index
- parse sample sheet
- assess_batch_file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/40)

v1.5.0 general functions

---

multi_workflow.py

- make functions redundant: make_ms_workflow_out_dir, get_ms_stage_input_dict, make_ms_dias_batch_file
- dry running
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/37)

v1.5.0 multi

---

single_workflow.py

- Remove make_ss_workflow_out_dir
- Remove run-dias_ss_batch_file
- dry running
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/35)

v1.5.0 single workflow

---

config.py

Uses dias_reports v1.0.1 for Athena v1.1.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/48)

update report workflow id for 1.5.1

---

config.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/52)

update report workflow ID

---

config.py

reports workflow v1.0.4
- Athena to v1.1.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/53)

update report workflow ID to 1.0.4

---

dias.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/56)

change path to config file

---

multiqc.py

- Updated dx run command input specs for the multiQC app
- output: https://platform.dnanexus.com/projects/G7yQ6084k8jzVGqY4BFv09Xv/monitor/job/G82XKZ84k8jb46019Yp937qG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/62)

Dias 169 Update to handle new multiQC app

---

general_functions.py

Currently fails if dx describe stage names are too long. Replaced with dx describe json instead.
Output: https://platform.dnanexus.com/projects/G7yQ6084k8jzVGqY4BFv09Xv/monitor/analysis/G86bbgj4k8jb5ZgV49ZPzq5B
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/65)

RD 98 Use json describe to grab stages

---

reports.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/69)

not retrict other NA samples in the job report

---

multiqc.py
reports.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/70)

fix gathering of panel for the displaying of panels in generate workbook

---

reports.py

- Correctly pass lists of clinical indications and panels to variant workbooks
- Detect and filter out samples with symbols as panels. Pass this list to the job reports file. Fixes #74
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/75)

V1.9.2 - 2

---

ReadMe.md
cnvcalling.py
dias.py

- Takes in bam & bai files and runs GATKgCNV_call app
- example output: https://platform.dnanexus.com/projects/GFGYfjj4PygF2VvB4gvgyxQQ/monitor/job/GFJ9vqj4Pyg66B77FjKZzgfV
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/76)

GCNV-15 CNV integration dev

---

general_functions.py

- Searches both xls and xlsx for excel workbooks so cnvreports increment correctly.
cnvreports https://platform.dnanexus.com/projects/GGy14bQ4yx1jYBYF19gxKjy7/monitor/analysis/GGy4j6Q4yx1Q0kpZ4jX4XzK4 & cnvreanalysis https://platform.dnanexus.com/projects/GGy14bQ4yx1jYBYF19gxKjy7/monitor/analysis/GGy53Zj4yx1jYBYF19gxP32z
CNV reanalysis has "_3" output and CNV reports has "_2"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/88)

GCNV-59 Search xls and xlsx reports

---

cnvreports.py
reports.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/98)

DI-141 upload manifest

---

cnvreports.py
reports.py

https://cuhbioinformatics.atlassian.net/browse/DI-293
example job with corrected output filename: https://platform.dnanexus.com/projects/GQG6Gq04PZpv8ykZpgVPyK0V/monitor/job/GVXJBBj4PZpZ6X14280qj9gg
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/103)

add output_file_prefix string input to generate_bed stages

---

cnvcalling.py
dias.py
reports.py

for NG-240
the -m or --mosaic flag switches reports over to use mosaic vcf (produced outside of dias script)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/108)

add mosaics flag

---

reports.py

batch was still pointing to the normal report dynamic files rather than the new mosaicreports ones
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/110)

fix lack of dynamic files for mosaics

---

dxapp.json
notes.md
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py
resources/home/dnanexus/dias_batch/utils/utils.py

- Added function to parse both Epic and Gemini manifests
- Made reading of dx files into a more generic function with better checking (`DXManage.read_dxfile()`)
- Added function with optional input to split test codes to generate sample reports
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/112)

Smaller changes before reports launching fun comes

---

.gitignore
dxapp.json
readme.md
resources/home/dnanexus/dias_batch/dias_batch.py

Add additional input of `-iexclude_samples_file` in addition to `-iexclude_samples`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/117)

Additional input: -iexclude_samples_file

---

.gitignore
dxapp.json
example/dias_batch_example_config.json
readme.md
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/pytest.ini
resources/home/dnanexus/dias_batch/utils/dx_requests.py

Functionality added to launch eggd_artemis after all other jobs complete
- additional boolean input mode for running the app
- additional file input of QC xlsx
- additonal `DXExecute.artemis()` to handle config and launching job
- additional checks in `CheckInputs` for checking inputs valid
- minor change to `DXExecute.terminate()` to ensure apps terminate before workflows to not cause it to fail in testing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/118)

Handle launching eggd_artemis

---

dxapp.json
readme.md
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py

Handle archived files better, will either exit with a list of files required that are not live to not fail on trying to launch jobs, or if `-iunarchive=true` unarchiving will be automatically triggered
- additional input `-iunarchive` added to control if to unarchive
- additional functions:
- `DXManage.check_archival_state()`  to check a list of files for being in a non-live state
- `DXManage.unarchive()` to do the actual unarchiving
Closes #116 
n.b. I haven't actually tested this yet as I didnt want to start unarchiving lots of files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/119)

Handle archived files nicely

---

example/dias_batch_example_config.json
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py
resources/home/dnanexus/dias_batch/utils/utils.py

Minor fixes after writing unit tests for running as app
- add lots of spacing to prints dumped into logs for readability
- move setting workspace ID before checking inputs to fix searching dnanexus
- make artemis only run if some snv or cnv jobs run
- pass and use `exclude_samples` in cnv reports to get better message for summary report
- don't try launch jobs on empty manifest
- set output prefix for workbooks in CNV reports
- pass excluded samples to summary report
- fix for getting config file name from dx describe call
Example run of app to launch SNV and CNV reports: https://platform.dnanexus.com/projects/GZ025k04VjykZx3bKJ7YP837/monitor/job/GZFXvYj4VjyggGq9xXKb6qp8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Minor app fixes

---

dxapp.json
readme.md
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_utils.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py
resources/home/dnanexus/dias_batch/utils/utils.py

- Add `-isubset_manifest` as an optional input to the app to be able to run jobs on only certain samples
- Remove old `exclude_samples` input from ` DXExecute.reports_workflow` that was unused
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/130)

Add subset as an input

---

resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/tests/test_utils.py
resources/home/dnanexus/dias_batch/utils/utils.py

Fix typos to tidy up before testing, no functional changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/140)

fix typos and whitespace cleanup

---

dxapp.json
readme.md
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py

- Add missing `assay_config_dir` to app input spec
- Minor rewording to readme
- Fix broken unit test
- Example job: https://platform.dnanexus.com/projects/GZ025k04VjykZx3bKJ7YP837/monitor/job/GbPgb404Vjyp815pVF79FqZk
- Tests passing:
```
jethro@jethro-T490:~/Projects/dias_batch_running$ python3 -m pytest resources/home/dnanexus/dias_batch/tests/
==================================================================================================== test session starts ====================================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/jethro/Projects/dias_batch_running/resources/home/dnanexus/dias_batch, configfile: pytest.ini
plugins: Faker-14.0.0, subtests-0.11.0, html-4.1.0, …
```

Assay config dir as input

---

resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py

- Fixes for unarchiving files needed for analysis
- Remove check of config dir files when config file specified
Example job: https://platform.dnanexus.com/projects/GZ025k04VjykZx3bKJ7YP837/monitor/job/GbQJBKj4VjyZygZz8Qpx6vzp
Tests passing:
```
jethro@jethro-T490:~/Projects/dias_batch_running$ python3 -m pytest  resources/home/dnanexus/dias_batch/tests/
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/jethro/Projects/dias_batch_running/resources/home/dnanexus/dias_batch, configfile: pytest.ini
plugins: Faker-14.0.0, subtests-0.11.0, html-4.1.0, metadata-3.0.0, mock-3.11.1, …
```

Fix unarchiving

---

readme.md
resources/home/dnanexus/dias_batch/dias_batch.py

Fix input checking for eggd_artemis:
- make only SNV or CNV reports optional
- make QC xlsx optional
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/144)

V3.0.0 testing fixes - artemis inputs

---

readme.md

edit readme to add line about how `--manifest_subset` would be used
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/146)

add more specific info about use case for manifest_subset

---

.github/workflows/pytest.yml
.gitignore
readme.md
requirements.txt

- add YAML for github actions to run pytest on pull requests
- add requirements.txt
- add pretty readme badge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/149)

V3.0.0 actions

---

example/dias_batch_example_config.json
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py

- switch unarchiving from dxpy.DXFile.unarchive -> dxpy.api.project_unarchive
- fixes #151 
-  add bonus check for bam files being found before launching CNV calling + additional unit test
- update example config file
Example job: https://platform.dnanexus.com/panx/projects/GbQ9gJ04ZxYYZ5JPk3GVVjGp/monitor/job/GbgY1G84ZxYZVV0987q9kKpx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/154)

v3.0.0 - switch unarchiving

---

example/dias_batch_example_config.json
readme.md
resources/home/dnanexus/dias_batch/utils/dx_requests.py

- enable passing through stage instance types for reports workflows from config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/159)

v3.0.0 - configure instance types for reports workflow stages

---

resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/utils/utils.py

- minor patch to allow running as an applet for easier testing and debugging
- test job running as app: https://platform.dnanexus.com/panx/projects/GbQ9gJ04ZxYYZ5JPk3GVVjGp/monitor/job/GbqX6bQ4ZxYfJq2jVxFBvF2B
- test job running as applet: https://platform.dnanexus.com/panx/projects/GbQ9gJ04ZxYYZ5JPk3GVVjGp/monitor/job/GbqX7604ZxYV3kG8jBK0BZk4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/161)

v3.0.0 applet patch

---

resources/home/dnanexus/dias_batch/dias_batch.py

Add small if/else loop to avoid referring to url_duration in function call if it is not set in the config
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/167)

add if/else loop

---

dxapp.json
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/tests/test_utils.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py
resources/home/dnanexus/dias_batch/utils/utils.py

Adds default behaviour to exclude control samples from CNV calling based on regex pattern
- switch matching of excluding samples to use `re.match` to handle control pattern
- add additional unit tests for utils.check_exclude_samples()`
- fixes #168
- fixes #169 
- fixes #170
Test job where CNV calling was laucnhed: https://platform.dnanexus.com/panx/projects/GfBY2K84bkgxbx7y3z6q83k9/monitor/job/GfBZqXj4bkgQ3YjV8QfF8ppK
From the above job logs: 
Querying launched CNV calling job to show control samples excluded correctly:
```
$ dx describe --json --verbose job-GfBZx0Q4bkgYz4YQgfx9v83p | jq -r '.input.bambais[][].describe.name' | wc -l
190
$ dx describe --json --verbose job-GfBZx0Q4bkgYz4YQgfx9v83p | jq -r '.input.bambais[][].describe.name' …
```

v3.1.0 default exclude controls

---

dxapp.json
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dias_batch.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py
resources/home/dnanexus/dias_batch/utils/utils.py

- pretty print in logs samples specified to exclude
- make `-iassay` optional input
- add additional check for `-iassay` and `-iassay_config_file` being specified
- add additional unit test
- minor reformat
- increase app version v3.0.1 -> v3.1.0
- fixes #172 
- fixes #173
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/175)

v3.1.0 make assay optional, improve logging

---

readme.md

Update readme with new input added in #171
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/176)

add details on exclude_controls to readme

---

resources/home/dnanexus/dias_batch/utils/utils.py

- small change to be able to handle parsing both current and new genepanels file, that has an additional column of PanelApp ID
- test job with config specifying a test version of upcoming new genepanels file: https://platform.dnanexus.com/panx/projects/GfBY2K84bkgxbx7y3z6q83k9/monitor/job/GfqpY1j4bkgvQyY2yP6GqGPV
- genepanels file tested with: `file-Gfqkb604bkgz7F9k1y86VbBj`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/185)

v3.1.0 - handle new genepanels

---

.github/workflows/pytest.yml
dxapp.json
readme.md
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/tests/test_utils.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py
resources/home/dnanexus/dias_batch/utils/utils.py

merging completed release to main
see https://cuhbioinformatics.atlassian.net/wiki/spaces/DV/pages/3100770334/eggd+dias+batch+v3.1.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/194)

V3.1.0 release

---

dxapp.json
resources/home/dnanexus/dias_batch/dias_batch.py
resources/home/dnanexus/dias_batch/tests/test_utils.py
resources/home/dnanexus/dias_batch/utils/utils.py

- Fixes #199 
- Improves the recording of parsed samples from manifest in summary text
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/203)

DI-930 fix #199 - improve summary text

---

.coveragerc

- update path in `.coveragerc`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/210)

IN-930 - update .coveragerc path

---

readme.md

- add more detail on dynamic inputs to readme
- fixes #206
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/211)

IN-930 - update readme

---

requirements.txt
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/utils/defaults.py

- adds multiQC html pattern to unarchive for artemis
- fix tests for new changes
- bump `packaging` -> 24.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/212)

IN-930 - add multiqc html pattern to defaults.py

---

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/utils/dx_requests.py

- fix #214 
- additional unit test to show fix works
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/215)

IN-930 - fix #214 single gene report name

---

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
resources/home/dnanexus/dias_batch/utils/defaults.py

- update default unarchive patterns for per sample gCNV bed files for eggd_artemis
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/216)

IN-930 - update default unarchive patterns
