cnvcalling.py
Have attempt folder outputs for cnv calling output as: `appname_appversion-assayname_assayversion-date-attempt`
- before: https://platform.dnanexus.com/projects/GFGYfjj4PygF2VvB4gvgyxQQ/data/output/dias_single_v1.3.0-CEN_v1.0.1-220113-1/eggd_GATKgCNV_call
- after: https://platform.dnanexus.com/projects/GFGYfjj4PygF2VvB4gvgyxQQ/data/output/dias_single_v1.3.0-CEN_v1.0.1-220113-1/eggd_GATKgCNV_call_v1.0.0-CEN_v1.1.5-220822-1
Allow input of first sampleID from samplename as excluded list rather than whole app
More testings: https://cuhbioinformatics.atlassian.net/wiki/spaces/C/pages/2738814981/CEN+Dias+batch+placeholder+title
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias …
=> GCNV-15 integration of cnv app with dias batch

ReadMe.md, cnvcalling.py, cnvreports.py, dias.py, general_functions.py
- New `cnvreports.py` script to handle CNV report and reanalysis generation. Very similar to `reports.py` but using different stage IDs from CEN Config (refer new stage IDs here: https://github.com/eastgenomics/egg5_dias_CEN_config/blob/CNV_integration_dev/egg5_config.py)
- Modification of `prepare_batch_writing` function to remove hardcoding of stage ID and flexibility of using function for CNVreports or reports (currently hard coded with athena stage IDs which isn't used in CNV reporting). This will require making changes to reports.py to update arg inputs for this function but will do this changes in the CNV_dev -> main PR later on :)
- Modified CNVcalling output folder to be `appname_appversion-assay_assayversion-date-attempt`
- Modification of `get_stage_inputs` to allow the specific …
=> GCNV-32 dias batch for cnv reports & small enhancement for cnvcalling

cnvcalling.py
Samples can be excluded from CNV calling and this is provided in a tsv when running dias batch. This file will be uploaded into the CNV calling app directory and named "excluded_list.tsv".
The full sample name is needed to differentiate the samples if there are repeated ones. Currently, only the first field is used. Now, the full sample name will be used up to EGG. If a sample in the excluded list does not have EGG, an error will be raised.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/89)
=> GCNV-96 dias batch v1.10.2 CNVcalling amendments

cnvreports.py
Keeps the sample list (derived from the samplesheet) where CNV VCFs were generated from the cnvcalling app. This overrides the bug where if a sample has no CNV VCF, dias batch does not say that the inputs for a sample is not found.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/90)
=> GCNV-96 dias batch v1.10.2 CNVreports amendments

cnvreports.py, dias.py, general_functions.py, reports.py
`dias.py`: 
- added egg code for FH assay, corrected path for CEN config on the cluster.
`general_functions.py`: 
- rename the argument to a more general `input_dir` instead of `ss_workflow_out_dir` in the `get_stage_inputs` function
`reports.py`: 
- added docstrings and corrected comments
- added logic to check that reports workflow is only set off for samples that are on the SampleSheet for the run AND have output files from the corresponding dias_single_workflow
`cnvreports.py`: 
- docstrings and wording of comments similar to reports.py
- adjust variable names to fit with generating reports from CNV calling output and not directly from dias_single output
- added logic to check that CNVreports workflow is only set off for samples that are on the SampleSheet for the run AND have output …
=> Fix variable names in cnvreports script

ReadMe.md, cnvcalling.py, dias.py
The output directory structure has changed since eggd_conductor is used to automatically set off dias_single, dias_multi and MultiQC. 
* In the `cnvcalling.py` script there were hard coded requirements for the input path to include the string "single" as this is what used to be the name of the dias_single workflow's output directory, which has now changed to be the assay name and datetime stamp only (eg `CEN-230407_2148`). This assertion has now been removed. [0f2a1f8](https://github.com/eastgenomics/dias_batch_running/commit/0f2a1f86f4c67cff0643827f860cc4b5e04f62bc)
* Also in the `cnvcalling.py` script, "EGG" codes were required to be in the sample name from the exclusion.txt input to the script. This will no longer be available with Epic sample naming, therefore the logic of collecting …
=> DI-225 adjustment to CNVcalling due to automation

reports.py
TWE config file doesn't have cnvcalling_inputs therefore "sentieon" folder name could be hard-coded
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/99)
=> Update logic for finding sentieon VCFs

cnvreports.py
cnvreports script doesn't have a `rpt_workflow_out_dir` variable, because it is called `cnvrpt_workflow_out_dir`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/100)
=> correct cnvrpt_workflow_out_dir

resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/pytest.ini, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Unit tests for functions in `utils.dx_requests.py`, these are mostly for functions managing and findings files in DNAnexus under `DXManage()`
- separate out reading of assay config file provided to `-iassay_config_file()` to its own function (`DXManage.read_assay_config_file()`) from searching in DNAnexus for one
- Fix correctly getting highest version config file by using `packaging.version.Version`
- unit tests added to `test_dx_requests.py`
```
jethro@jethro-T490:~/Projects/dias_batch_running$ python3 -m pytest -v resources/home/dnanexus/dias_batch/tests/
========================================================================================================== test session starts ========================================================================================================== …
```
=> Unit tests for dx_requests.py

resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dias_batch.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Unit tests for `CheckInputs` in dias_batch.py, these are all functions that run when the app starts to validate the inputs provided. This is likely to have more tests added as more checks are added once I think of everything needed for each mode, but its a start.
- fix some bits of bugs in the checks highlighted by the tests
- added tests to `test_dias_batch.py`
```
jethro@jethro-T490:~/Projects/dias_batch_running$ python3 -m pytest -v resources/home/dnanexus/dias_batch/tests/
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3 …
```
=> Unit tests for CheckInputs

resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/pytest.ini, resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/utils.py
- unit tests added for `.filter_manifest_samples_by_files()`, `split_manifest_tests()` and `add_panel_and_indications_to_manifest()`
- fix to actually call `exclude_samples()` if specified
- minor change to sort the test lists to make testing work
```
jethro@jethro-T490:~/Projects/dias_batch_running$ python3 -m pytest -vvvv --cov resources/home/dnanexus/dias_batch/
====================================================== test session starts =======================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/dias_batch_running
plugins: Faker-14.0.0, mock-3.9.0, cov-4.0.0
collected 51 items …
```
=> More unit tests for utils

resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/pytest.ini, resources/home/dnanexus/dias_batch/tests/test_data/example_config.json, resources/home/dnanexus/dias_batch/tests/test_data/example_filled_config.json, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py, resources/home/dnanexus/dias_batch/utils/utils.py
More unit tests, test coverage now at 100% for all of `utils.py` and 100% for `dx_requests.DXManage`, plus addition unit tests started for `dx_requests.DXExecute.cnv_calling`
- shifted getting job and app details to `dias_batch.main` from `utils.write_summary_report` to make testing easier
- Additional unit tests for `dx_requests.DXManage`
- switched to use of `setUp()` and `tearDown()` test functions to reduce use of decorators (will refactor more later to clean up where needed)
- additional tests for `utils.py`
- tests for summary report writing
- other minor tests to get to 100% coverage
-  fix making cnv_calling output path have consistent time stamp as other jobs
```
---------- coverage: platform linux, python 3.8.10-final-0 -----------
Name …
```
=> Lots more unit tests and some bug fixes

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
- handle files in state of `archiving` or `unarchiving` better to not raise an error
- specify project to call `DXFile.unarchive()` within
- add unit test for the above
```
---------- coverage: platform linux, python 3.8.10-final-0 -----------
Name                                                           Stmts   Miss  Cover
----------------------------------------------------------------------------------
resources/home/dnanexus/dias_batch/__init__.py                     0      0   100%
resources/home/dnanexus/dias_batch/dias_batch.py                 146     96    34%
resources/home/dnanexus/dias_batch/tests/__init__.py               0      0   100%
resources/home/dnanexus/dias_batch/tests/test_dias_batch.py       63      0   100% …
```
=> Improve handling of files for unarchiving

readme.md, resources/home/dnanexus/dias_batch/tests/test_dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Many more unit tests for `DXExecute.reportsworkflow`, plus some minor changes to raising errors etc
Now at 100% test coverage for dx_requests.py :tada:
```
---------- coverage: platform linux, python 3.8.10-final-0 -----------
Name                                                           Stmts   Miss  Cover
----------------------------------------------------------------------------------
resources/home/dnanexus/dias_batch/__init__.py                     0      0   100%
resources/home/dnanexus/dias_batch/dias_batch.py                 146     96    34%
resources/home/dnanexus/dias_batch/tests/__init__.py               0      0   100%
resources/home/dnanexus/dias_batch/tests/test_dias_batch.py       63      0   100%
resources/home/dnanexus/dias_batch/tests/test_dx_requests.py     400 …
```
=> Unit tests for DXExecute.reports_workflow

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Fix broken tests in `test_dx_requests.py`
```
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/dias_batch_running/resources/home/dnanexus/dias_batch, configfile: pytest.ini
plugins: Faker-14.0.0, mock-3.11.1, cov-4.0.0
collected 103 items                                                                                                                   
resources/home/dnanexus/dias_batch/tests/test_dias_batch.py::TestCheckInputs::test_invalid_assay_str_error_raised PASSED        [  0%]
resources/home/dnanexus/dias_batch/tests/test_dias_batch.py::TestCheckInputs::test_assay_config_dir PASSED                      [  1%]
resources/home/dnanexus/dias_batch/tests/test_dias_batch.py::TestCheckInputs::test_check_single_output_dir PASSED               [  2%] …
```
=> fix for broken tests in test_dx_requests.py

dxapp.json, readme.md, resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py, resources/home/dnanexus/dias_batch/utils/utils.py
Handle array of manifest files to be able to process runs in one go where samples are split between Gemini and Epic manifest files
- `-manifest_file` input changed to `-imanifest_files`
- manifest source (Epic or Gemini) now stored in manifest dict after parsing each manifest to pass to reports workflow calling
- fixed unit tests for new behaviour
Examples jobs:
- Epic + Gemini manifest: https://platform.dnanexus.com/projects/GZ025k04VjykZx3bKJ7YP837/monitor/job/Gb4P7284Vjyzjx13Kv0FpKpf
- single Epic manifest: https://platform.dnanexus.com/projects/GZ025k04VjykZx3bKJ7YP837/monitor/job/Gb4PV204VjygxP8bkGjZk648
- single Gemini manifest: https://platform.dnanexus.com/projects/GZ025k04VjykZx3bKJ7YP837/monitor/job/Gb4PV4Q4Vjyg7k91534G5q34
Unit tests passing:
```
Jethros-MBP:dias_batch_running …
```
=> Array manifest input

resources/home/dnanexus/dias_batch/utils/dx_requests.py
use `sorted()` to ensure when both Epic and Gemini manifests specified that they will always be in the expected order
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/139)
=> More robustly handle parsing of both Epic and Gemini manifests

resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/utils.py
Tests passing:
```
jethro@jethro-T490:~/Projects/dias_batch_running$ python3 -m pytest resources/home/dnanexus/dias_batch/tests/
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/jethro/Projects/dias_batch_running/resources/home/dnanexus/dias_batch, configfile: pytest.ini
plugins: Faker-14.0.0, subtests-0.11.0, html-4.1.0, metadata-3.0.0, mock-3.11.1, cov-4.0.0
collected 103 items …
```
=> Fix to improve single gene parsing

.gitignore, resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py, resources/home/dnanexus/dias_batch/utils/utils.py
- Add function `utils.check_exclude_samples()` to check for sample names provided to `-exclude_samples` that they are valid before CNV calling and CNV reports
- Add tests for new function
- Add check for file ID being provided to `exclude_samples` instead of `exclude_samples_file`
- Add additional check for the above
- Add `strip()` to `single_output_dir` input to ensure no annoying whitespace errors
- Example job with `-icnv_call` and invalid exclude sample: https://platform.dnanexus.com/projects/GbQ9gJ04ZxYYZ5JPk3GVVjGp/monitor/job/GbXJX604ZxYZygZz8QpxKv98
- Example job with `-icnv_reports` and invalid exclude sample: https://platform.dnanexus.com/projects/GbQ9gJ04ZxYYZ5JPk3GVVjGp/monitor/job/GbXJZy04ZxYyqvB36vJ5124x
- Tests passing:
```
Jethros-MBP:dias_batch_running jethro$ python3 -m …
```
=> v3.0.0 testing fixes - improve checking of exclude_samples

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py, resources/home/dnanexus/dias_batch/utils/utils.py
- add check for athena version in reports workflow, for >=v1.6.0 will add new `indication` input
- added unit tests for new `utils.check_athena_version()`
- fix unit tests for `dx_requests.DXExecute.reports_workflow` with added function call patched
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/150)
=> v3.0.0 - athena version check

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Fix for correctly finding project context of a given file by using `dxpy.DXFile.list_projects` over `dxpy.find_data_objects()`, previously would incorrectly find files with duplicate name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/153)
=> v3.0.0 - fix DXManage.get_file_project_context

resources/home/dnanexus/dias_batch/utils/utils.py
New DNAnexus UI makes the logs worse and strips all leading tabs/whitespace, which results in any dicts in the logs being a single level and being unreadable, this fixes this by indenting using non-standard whitespace character which isn't removed and reverts back to how it looked in the previous logs with the prettier printing
Before:
After: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/155)
=> v3.0.0 - make the logs great again

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Change when searching for BAM files for CNV calling to specify sub dir instead of including in initial search path to handle incomplete path names
Test job: https://platform.dnanexus.com/panx/projects/GbQ9gJ04ZxYYZ5JPk3GVVjGp/monitor/job/GbgYx6Q4ZxYb69Qvy3z1QXv0
From logs: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/157)
=> v3.0.0 - fix bam searching

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py
- fix formatting of unit test message that broke test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/156)
=> v3.0.0 - fix for formatting in unit test

dxapp.json, readme.md, resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dias_batch.py
Test job to see that correct error is raised
https://platform.dnanexus.com/panx/projects/GbQ9gJ04ZxYYZ5JPk3GVVjGp/monitor/job/GbqVBqQ4ZxYXf1p6jpPKKgxZ
This used a fastq as the QC status input and has the correct error message:
Job : https://platform.dnanexus.com/panx/projects/GbQ9gJ04ZxYYZ5JPk3GVVjGp/monitor/job/GbqVGG84ZxYy5JJfjfGY20GK
Launches all required jobs:
This fails due to it being an applet, not an app, but the .xlsx testing does work
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/160)
=> Check QC file is an .xlsx report

resources/home/dnanexus/dias_batch/dias_batch.py
drop `dxid=` reference from describe call
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/dias_batch_running/162)
=> v3.0.0 - fix patch for applet build

dxapp.json, resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Update eggd_dias_batch to be able to parse url_duration from the config and pass on to eggd_artemis. This means url_duration can be set from the config. eggd_dias_batch was built as an applet to test (applet-Gf6k3PQ46k5F095GgvQ2GYYy)
Example eggd_dias_batch job with url duration set from config: https://platform.dnanexus.com/panx/projects/Gf6fPz046k5582p9PvFYf8ZZ/monitor/job/Gf7F8X046k50YGyyqK3YyK43
Example artemis job launched by above batch job showing that url duration is now set as 15811200 from the config, rather than 4838400 which is the default: https://platform.dnanexus.com/panx/projects/Gf6fPz046k5582p9PvFYf8ZZ/monitor/job/Gf7F9pj46k5PzPX3ZF4G8VGY
Resulting .xlsx expires 29/6/2024 which is in six months:
Delete unused warning from dias_batch script to address #165
- - -
This …
=> Di 641 v3.0.1

.github/workflows/pytest.yml, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Fixes issue where a trailing blank line in a file would result in the file contents having an empty string when read in, this would break excluding samples as all files would match the empty string and be excluded
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/174)
=> v3.1.0 fix trailing blank line

resources/home/dnanexus/dias_batch/dias_batch.py
minor change to reduce lines in log file from pretty printing the parsed manifest(s)
before: 
after: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/177)
=> v3.1.0 - tidy up manifest logging

dxapp.json, readme.md, resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
- adds optional app input `-imultiqc_report` to be able to specify a multiQC report to eggd_artemis >=1.4.0
- fixes #179 
- test job with current config `-imultiqc_report`: https://platform.dnanexus.com/panx/projects/GfBY2K84bkgxbx7y3z6q83k9/monitor/job/GfY6x3Q4bkgQBG2GxjzVzQV3
- n.b. not tested trying to run eggd_artemis/1.4.0 since DNAnexus doesn't want to allow an unpublished app to be run from an app environment, have added additional unit test to show when new version of eggd_artemis is used that the multiqc_report file ID is passed into the job inputs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/180)
=> v3.1.0 - add optional multiqc_report input for eggd_artemis

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
- additional check for only one config file of a given version found, this ensures we unambiguously can select the correct file to use in the case of errors
- addresses https://github.com/eastgenomics/egg5_dias_CEN_config/issues/53
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/182)
=> v3.1.0 - error on multiple configs

resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/utils.py
- handle many ways of them adding in 'Rearch Use' as a test code to skip
- fixes #181
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/183)
=> v3.1.0 - better handle research use test code

readme.md, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py, resources/home/dnanexus/dias_batch/utils/utils.py
Small update to remove hardcoded stages -> string inputs such as clinical indication and panels, these should now be defined in the config with placeholder text for greater flexibility
- add function `utils.add_dynamic_inputs()` to parse in placeholder strings
- add unit tests for new function
- remove old hardcoded stage inputs
- remove unneeded function `utils.check_athena_version()` as the input this added can now be defined from the config
Example config with placeholder inputs in: https://platform.dnanexus.com/panx/projects/GfBY2K84bkgxbx7y3z6q83k9/data/?scope=project&id.values=file-GfkyF3j4bkgXfKXvX1P3Yzx5
Test job launching reports: https://platform.dnanexus.com/panx/projects/GfBY2K84bkgxbx7y3z6q83k9/monitor/job/GfkyF804bkgY1xGf5x3ZjP9q
- - -
This change is [<img …
=> v3.1.0 - handle dynamic inputs

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
adds in running mode for SNV and mosaic to the reports workflow output directory name to fix #186 
for CNVs this is omitted since the reports workflow name is different and contains CNV so therefore would be redundant.
Example new directory output naming would be:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/188)
=> v3.1.0 - add running mode to reports folder output name

resources/home/dnanexus/dias_batch/dias_batch.py
- fix issue where manifest files specified with project- prefix raises an error
- fixes #189 
Test job with project specified: https://platform.dnanexus.com/panx/projects/GfBY2K84bkgxbx7y3z6q83k9/monitor/job/GfyXBG84bkgq8722B5QgZ23V
```
$ dx run app-GfG4Bf84QQg40v7Y6zKF34KP -iassay=CEN -isingle_output_dir="project-Gfxvyxj49Z1jbVZbXyy23BfP:/output/CEN-240201_1705" -isnv_reports=true -icnv_reports=true -icnv_call_job_id=job-GfyKf2Q49Z1vj7pbGxfvZQv8 -iartemis=true -itesting=true -iqc_file=project-Gfxvyxj49Z1jbVZbXyy23BfP:file-GfyJzkj49Z1Vp78GGXXZJjXB -iexclude_samples="127545356-24016Q0016-24NGCEN10-9527-0-99347387" -imanifest_files=project-Gfxvyxj49Z1jbVZbXyy23BfP:file-GfyKZ0Q49Z1Q3Jykf2ZjB9Yq -y -isample_limit=1 --tag 'with project prefix'
Using input JSON:
{
"assay": "CEN", …
```
=> v3.1.0 - handle manifest with project

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py, resources/home/dnanexus/dias_batch/utils/utils.py
- fix returning BAM files excluded from CNV calling as list of file names instead of describe details
- fixes #191 
- add additional unit tests to better test report summary writing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/192)
=> v3.1.0 - fix reports summary writing

dxapp.json
- changes `split_tests` to default to true to fit with new optimised filtering app
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/193)
=> switch split_tests to default to true

resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
- Fixes #195
- Corrects behaviour where the intervals bed file from CNV calling to go to CNV reports would wrongly get removed from checking for files to unarchive, and as such would not be unarchived
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/200)
=> DI-930 fix #195 - correctly check all archived files

resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/utils.py
- Fixes #197 
- Fixes where samples with no test codes were being skipped instead of raising an error, will now correctly raise a RuntimeError
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/201)
=> DI-930 fix #197 - fix skipping samples with missing test codes

resources/home/dnanexus/dias_batch/tests/test_utils.py, resources/home/dnanexus/dias_batch/utils/utils.py
- Fixes #198 
- When an invalid sample identifier / missing is present in the manifest, this would normally raise an error on parsing
- This will now not raise an error if `-isubset` is provided, and all sample IDs provided to `-isubset` are valid
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/202)
=> DI-930 fix #198 - allow invalid samples in manifest when subsetting

resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dias_batch.py
- adds new function `CheckInputs.strip_string_inputs` to ensure all string inputs have no leading / trailing whitespace
- fixes #207 
- add unit test for new function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/208)
=> DI-930 fix #207 strip whitespace from inputs

readme.md, resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/defaults.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
Improves checking of archived files before attempting to launch any jobs to fix #196 
- addition of `dx_requests.check_all_files_archival_state`
- function checks running modes selected and searches for all defined file types for each sample in manifest, and then calls `dx_requests.check_archival_state` to determine if any files for any jobs will be archived
- add required patterns for files to `utils.defaults`
- this will also be able to be defined in the assay config file to overwrite this as needed
- add unit tests for new functionality
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/209)
=> IN-930 - fix #196 better unarchival checking

dxapp.json, readme.md, requirements.txt, resources/home/dnanexus/dias_batch/dias_batch.py, resources/home/dnanexus/dias_batch/tests/test_dx_requests.py, resources/home/dnanexus/dias_batch/utils/dx_requests.py
- adds new input `unarchive_only` to control just checking archivalState and unarchiving (i.e. no running of jobs)
- additional unit tests added for behaviour
- bump packaging -> 24.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_dias_batch/213)
=> IN-930 add new input unarchive only
